# frozen_string_literal: true

module ::DiscourseSocialProfile
  module DefaultPlatforms
    DATA = [
    {
      key: "email",
      position: "0",
      enabled: true,
      label: "Email",
      user_instructions: "Enter the email address you want to link from your profile.",
      placeholder: "name@example.com",
      input_type: "email",
      base_url: nil,
      allowed_hosts: nil,
      path_regex: nil,
      icon_name: "envelope",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Email",
      builtin: true,
    },
    {
      key: "facebook",
      position: "1",
      enabled: true,
      label: "Facebook",
      user_instructions: "Enter your Facebook username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.facebook.com/",
      allowed_hosts: "facebook.com,www.facebook.com,m.facebook.com",
      path_regex: nil,
      icon_name: "fab-facebook",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Facebook",
      builtin: true,
    },
    {
      key: "instagram",
      position: "2",
      enabled: true,
      label: "Instagram",
      user_instructions: "Enter your Instagram username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.instagram.com/",
      allowed_hosts: "instagram.com,www.instagram.com",
      path_regex: nil,
      icon_name: "fab-instagram",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Instagram",
      builtin: true,
    },
    {
      key: "threads",
      position: "3",
      enabled: true,
      label: "Threads",
      user_instructions: "Enter your Threads username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.threads.net/@",
      allowed_hosts: "threads.net,www.threads.net",
      path_regex: nil,
      icon_name: "fab-threads",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Threads",
      builtin: true,
    },
    {
      key: "x",
      position: "4",
      enabled: true,
      label: "X",
      user_instructions: "Enter your X username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://twitter.com/",
      allowed_hosts: "twitter.com,www.twitter.com,x.com,www.x.com",
      path_regex: nil,
      icon_name: "fab-twitter",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Twitter",
      builtin: true,
    },
    {
      key: "linkedin",
      position: "5",
      enabled: true,
      label: "LinkedIn",
      user_instructions: "Enter the full HTTPS URL to your LinkedIn profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "linkedin.com,www.linkedin.com",
      path_regex: "^/(in|company|school|pub)/[^/?#]+/?$",
      icon_name: "fab-linkedin-in",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "LinkedIn Profile",
      builtin: true,
    },
    {
      key: "youtube",
      position: "6",
      enabled: true,
      label: "YouTube",
      user_instructions: "Enter your YouTube username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://youtube.com/@",
      allowed_hosts: "youtube.com,www.youtube.com",
      path_regex: nil,
      icon_name: "fab-youtube",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Youtube",
      builtin: true,
    },
    {
      key: "tiktok",
      position: "7",
      enabled: true,
      label: "TikTok",
      user_instructions: "Enter your TikTok username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://tiktok.com/@",
      allowed_hosts: "tiktok.com,www.tiktok.com",
      path_regex: nil,
      icon_name: "fab-tiktok",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Tiktok",
      builtin: true,
    },
    {
      key: "telegram",
      position: "8",
      enabled: true,
      label: "Telegram",
      user_instructions: "Enter your Telegram username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://t.me/",
      allowed_hosts: "t.me",
      path_regex: nil,
      icon_name: "fab-telegram",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Telegram",
      builtin: true,
    },
    {
      key: "github",
      position: "9",
      enabled: true,
      label: "GitHub",
      user_instructions: "Enter your GitHub username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://github.com/",
      allowed_hosts: "github.com,www.github.com",
      path_regex: nil,
      icon_name: "fab-github",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Github",
      builtin: true,
    },
    {
      key: "bluesky",
      position: "10",
      enabled: true,
      label: "Bluesky",
      user_instructions: "Enter your Bluesky username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://bsky.app/profile/",
      allowed_hosts: "bsky.app,www.bsky.app",
      path_regex: nil,
      icon_name: "fab-bluesky",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Bluesky",
      builtin: true,
    },
    {
      key: "strava",
      position: "11",
      enabled: true,
      label: "Strava",
      user_instructions: "Enter your numeric Strava user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://strava.com/athletes/",
      allowed_hosts: "strava.com,www.strava.com",
      path_regex: "^/athletes/\\d+",
      icon_name: "fab-strava",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Strava",
      builtin: true,
    },
    {
      key: "twitch",
      position: "12",
      enabled: true,
      label: "Twitch",
      user_instructions: "Enter your Twitch username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.twitch.tv/",
      allowed_hosts: "twitch.tv,www.twitch.tv",
      path_regex: nil,
      icon_name: "fab-twitch",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Twitch",
      builtin: true,
    },
    {
      key: "soundcloud",
      position: "13",
      enabled: true,
      label: "Soundcloud",
      user_instructions: "Enter your Soundcloud username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://soundcloud.com/",
      allowed_hosts: "soundcloud.com,www.soundcloud.com",
      path_regex: nil,
      icon_name: "fab-soundcloud",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Soundcloud",
      builtin: true,
    },
    {
      key: "spotify",
      position: "14",
      enabled: true,
      label: "Spotify",
      user_instructions: "Enter the full HTTPS URL to your Spotify profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "open.spotify.com",
      path_regex: "^(?:/(?:artist|track|album|playlist|show|episode)/[A-Za-z0-9]+|/user/[^/?#]+(?:/playlist/[A-Za-z0-9]+)?)/?$",
      icon_name: "fab-spotify",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Spotify",
      builtin: true,
    },
    {
      key: "bandcamp",
      position: "15",
      enabled: true,
      label: "Bandcamp",
      user_instructions: "Enter the full HTTPS URL to your Bandcamp profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: ".bandcamp.com,bandcamp.com,www.bandcamp.com",
      path_regex: nil,
      icon_name: "fab-bandcamp",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Bandcamp",
      builtin: true,
    },
    {
      key: "steam",
      position: "16",
      enabled: true,
      label: "Steam",
      user_instructions: "Enter the full HTTPS URL to your Steam profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "steamcommunity.com,www.steamcommunity.com",
      path_regex: "^/(id|profiles)/[^/?#]+/?$",
      icon_name: "fab-steam",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Steam",
      builtin: true,
    },
    {
      key: "mastodon",
      position: "17",
      enabled: true,
      label: "Mastodon",
      user_instructions: "Enter the full HTTPS URL to your Mastodon profile or page.",
      placeholder: "https://...",
      input_type: "url_any_https",
      base_url: nil,
      allowed_hosts: nil,
      path_regex: nil,
      icon_name: "fab-mastodon",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Mastodon",
      builtin: true,
    },
    {
      key: "tumblr",
      position: "18",
      enabled: true,
      label: "Tumblr",
      user_instructions: "Enter your Tumblr username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.tumblr.com/",
      allowed_hosts: "tumblr.com,www.tumblr.com,.tumblr.com",
      path_regex: nil,
      icon_name: "fab-tumblr",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Tumblr",
      builtin: true,
    },
    {
      key: "discord_profile",
      position: "19",
      enabled: true,
      label: "Discord (profile)",
      user_instructions: "Enter your numeric Discord (profile) user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://discord.com/users/",
      allowed_hosts: "discord.com,www.discord.com,discordapp.com,www.discordapp.com",
      path_regex: "^/users/\\d+",
      icon_name: "fab-discord",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Discord",
      builtin: true,
    },
    {
      key: "onlyfans",
      position: "20",
      enabled: true,
      label: "OnlyFans",
      user_instructions: "Enter your OnlyFans username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://onlyfans.com/",
      allowed_hosts: "onlyfans.com,www.onlyfans.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "onlyfans",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "OnlyFans",
      builtin: true,
    },
    {
      key: "fansly",
      position: "21",
      enabled: true,
      label: "Fansly",
      user_instructions: "Enter your Fansly username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://fansly.com/",
      allowed_hosts: "fansly.com,www.fansly.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "fansly",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Fansly",
      builtin: true,
    },
    {
      key: "fetlife",
      position: "22",
      enabled: true,
      label: "FetLife",
      user_instructions: "Enter your numeric FetLife user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://fetlife.com/users/",
      allowed_hosts: "fetlife.com,www.fetlife.com",
      path_regex: "^/users/\\d+",
      icon_name: "globe",
      builtin_icon: "fetlife",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "FetLife",
      builtin: true,
    },
    {
      key: "fancentro",
      position: "23",
      enabled: true,
      label: "FanCentro",
      user_instructions: "Enter your FanCentro username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://fancentro.com/",
      allowed_hosts: "fancentro.com,www.fancentro.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "fancentro",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "FanCentro",
      builtin: true,
    },
    {
      key: "linktree",
      position: "24",
      enabled: true,
      label: "Linktree",
      user_instructions: "Enter your Linktree username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://linktr.ee/",
      allowed_hosts: "linktr.ee,www.linktr.ee",
      path_regex: nil,
      icon_name: "link",
      builtin_icon: "linktree",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Linktree",
      builtin: true,
    },
    {
      key: "pornhub",
      position: "25",
      enabled: true,
      label: "Pornhub",
      user_instructions: "Enter your Pornhub username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.pornhub.com/users/",
      allowed_hosts: "pornhub.com,.pornhub.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "pornhub",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Pornhub",
      builtin: true,
    },
    {
      key: "amazon_wishlist",
      position: "26",
      enabled: true,
      label: "Amazon Wishlist",
      user_instructions: "Enter the full HTTPS URL to your Amazon Wishlist profile or page.",
      placeholder: "https://...",
      input_type: "url_any_https",
      base_url: nil,
      allowed_hosts: "amzn.to,.amazon.com,.amazon.co.uk,.amazon.de,.amazon.nl,.amazon.fr,.amazon.it,.amazon.es,.amazon.ca,.amazon.com.au",
      path_regex: nil,
      icon_name: "fab-amazon",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Amazon Wishlist",
      builtin: true,
    },
    ].freeze
  end
end
