# frozen_string_literal: true

module ::DiscourseSocialProfile
  module DefaultPlatforms
    DATA = [
    {
      key: "email",
      position: "0",
      enabled: true,
      label: "Email",
      user_instructions: "Enter the email address you want to link from your profile.",
      placeholder: "name@example.com",
      input_type: "email",
      base_url: nil,
      allowed_hosts: nil,
      path_regex: nil,
      icon_name: "envelope",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Email",
      builtin: true,
    },
    {
      key: "facebook",
      position: "1",
      enabled: true,
      label: "Facebook",
      user_instructions: "Enter your Facebook username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.facebook.com/",
      allowed_hosts: "facebook.com,www.facebook.com,m.facebook.com",
      path_regex: nil,
      icon_name: "fab-facebook",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Facebook",
      builtin: true,
    },
    {
      key: "instagram",
      position: "2",
      enabled: true,
      label: "Instagram",
      user_instructions: "Enter your Instagram username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.instagram.com/",
      allowed_hosts: "instagram.com,www.instagram.com",
      path_regex: nil,
      icon_name: "fab-instagram",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Instagram",
      builtin: true,
    },
    {
      key: "threads",
      position: "3",
      enabled: true,
      label: "Threads",
      user_instructions: "Enter your Threads username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.threads.net/@",
      allowed_hosts: "threads.net,www.threads.net",
      path_regex: nil,
      icon_name: "fab-threads",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Threads",
      builtin: true,
    },
    {
      key: "x",
      position: "4",
      enabled: true,
      label: "X",
      user_instructions: "Enter your X username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://twitter.com/",
      allowed_hosts: "twitter.com,www.twitter.com,x.com,www.x.com",
      path_regex: nil,
      icon_name: "fab-x-twitter",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Twitter",
      builtin: true,
    },
    {
      key: "linkedin",
      position: "5",
      enabled: true,
      label: "LinkedIn",
      user_instructions: "Enter the full HTTPS URL to your LinkedIn profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "linkedin.com,www.linkedin.com",
      path_regex: "^/(in|company|school|pub)/[^/?#]+/?$",
      icon_name: "fab-linkedin-in",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "LinkedIn Profile",
      builtin: true,
    },
    {
      key: "youtube",
      position: "6",
      enabled: true,
      label: "YouTube",
      user_instructions: "Enter your YouTube username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://youtube.com/@",
      allowed_hosts: "youtube.com,www.youtube.com",
      path_regex: nil,
      icon_name: "fab-youtube",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Youtube",
      builtin: true,
    },
    {
      key: "tiktok",
      position: "7",
      enabled: true,
      label: "TikTok",
      user_instructions: "Enter your TikTok username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://tiktok.com/@",
      allowed_hosts: "tiktok.com,www.tiktok.com",
      path_regex: nil,
      icon_name: "fab-tiktok",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Tiktok",
      builtin: true,
    },
    {
      key: "telegram",
      position: "8",
      enabled: true,
      label: "Telegram",
      user_instructions: "Enter your Telegram username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://t.me/",
      allowed_hosts: "t.me",
      path_regex: nil,
      icon_name: "fab-telegram",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Telegram",
      builtin: true,
    },
    {
      key: "github",
      position: "9",
      enabled: true,
      label: "GitHub",
      user_instructions: "Enter your GitHub username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://github.com/",
      allowed_hosts: "github.com,www.github.com",
      path_regex: nil,
      icon_name: "fab-github",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Github",
      builtin: true,
    },
    {
      key: "bluesky",
      position: "10",
      enabled: true,
      label: "Bluesky",
      user_instructions: "Enter your Bluesky username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://bsky.app/profile/",
      allowed_hosts: "bsky.app,www.bsky.app",
      path_regex: nil,
      icon_name: "fab-bluesky",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Bluesky",
      builtin: true,
    },
    {
      key: "strava",
      position: "11",
      enabled: true,
      label: "Strava",
      user_instructions: "Enter your numeric Strava user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://strava.com/athletes/",
      allowed_hosts: "strava.com,www.strava.com",
      path_regex: "^/athletes/\\d+",
      icon_name: "fab-strava",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Strava",
      builtin: true,
    },
    {
      key: "twitch",
      position: "12",
      enabled: true,
      label: "Twitch",
      user_instructions: "Enter your Twitch username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.twitch.tv/",
      allowed_hosts: "twitch.tv,www.twitch.tv",
      path_regex: nil,
      icon_name: "fab-twitch",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Twitch",
      builtin: true,
    },
    {
      key: "soundcloud",
      position: "13",
      enabled: true,
      label: "Soundcloud",
      user_instructions: "Enter your Soundcloud username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://soundcloud.com/",
      allowed_hosts: "soundcloud.com,www.soundcloud.com",
      path_regex: nil,
      icon_name: "fab-soundcloud",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Soundcloud",
      builtin: true,
    },
    {
      key: "spotify",
      position: "14",
      enabled: true,
      label: "Spotify",
      user_instructions: "Enter the full HTTPS URL to your Spotify profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "open.spotify.com",
      path_regex: "^(?:/(?:artist|track|album|playlist|show|episode)/[A-Za-z0-9]+|/user/[^/?#]+(?:/playlist/[A-Za-z0-9]+)?)/?$",
      icon_name: "fab-spotify",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Spotify",
      builtin: true,
    },
    {
      key: "bandcamp",
      position: "15",
      enabled: true,
      label: "Bandcamp",
      user_instructions: "Enter the full HTTPS URL to your Bandcamp profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: ".bandcamp.com,bandcamp.com,www.bandcamp.com",
      path_regex: nil,
      icon_name: "fab-bandcamp",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Bandcamp",
      builtin: true,
    },
    {
      key: "steam",
      position: "16",
      enabled: true,
      label: "Steam",
      user_instructions: "Enter the full HTTPS URL to your Steam profile.",
      placeholder: "https://...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "steamcommunity.com,www.steamcommunity.com",
      path_regex: "^/(id|profiles)/[^/?#]+/?$",
      icon_name: "fab-steam",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Steam",
      builtin: true,
    },
    {
      key: "mastodon",
      position: "17",
      enabled: true,
      label: "Mastodon",
      user_instructions: "Enter the full HTTPS URL to your Mastodon profile or page.",
      placeholder: "https://...",
      input_type: "url_any_https",
      base_url: nil,
      allowed_hosts: nil,
      path_regex: nil,
      icon_name: "fab-mastodon",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Mastodon",
      builtin: true,
    },
    {
      key: "tumblr",
      position: "18",
      enabled: true,
      label: "Tumblr",
      user_instructions: "Enter your Tumblr username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.tumblr.com/",
      allowed_hosts: "tumblr.com,www.tumblr.com,.tumblr.com",
      path_regex: nil,
      icon_name: "fab-tumblr",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Tumblr",
      builtin: true,
    },
    {
      key: "discord_profile",
      position: "19",
      enabled: true,
      label: "Discord (profile)",
      user_instructions: "Enter your numeric Discord (profile) user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://discord.com/users/",
      allowed_hosts: "discord.com,www.discord.com,discordapp.com,www.discordapp.com",
      path_regex: "^/users/\\d+",
      icon_name: "fab-discord",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Discord",
      builtin: true,
    },
    {
      key: "onlyfans",
      position: "20",
      enabled: true,
      label: "OnlyFans",
      user_instructions: "Enter your OnlyFans username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://onlyfans.com/",
      allowed_hosts: "onlyfans.com,www.onlyfans.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "onlyfans",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "OnlyFans",
      builtin: true,
    },
    {
      key: "fansly",
      position: "21",
      enabled: true,
      label: "Fansly",
      user_instructions: "Enter your Fansly username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://fansly.com/",
      allowed_hosts: "fansly.com,www.fansly.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "fansly",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Fansly",
      builtin: true,
    },
    {
      key: "fetlife",
      position: "22",
      enabled: true,
      label: "FetLife",
      user_instructions: "Enter your numeric FetLife user ID, or paste a full HTTPS URL for this platform.",
      placeholder: "123456789 or https://...",
      input_type: "numeric_id",
      base_url: "https://fetlife.com/users/",
      allowed_hosts: "fetlife.com,www.fetlife.com",
      path_regex: "^/users/\\d+",
      icon_name: "globe",
      builtin_icon: "fetlife",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "FetLife",
      builtin: true,
    },
    {
      key: "fancentro",
      position: "23",
      enabled: true,
      label: "FanCentro",
      user_instructions: "Enter your FanCentro username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://fancentro.com/",
      allowed_hosts: "fancentro.com,www.fancentro.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "fancentro",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "FanCentro",
      builtin: true,
    },
    {
      key: "linktree",
      position: "24",
      enabled: true,
      label: "Linktree",
      user_instructions: "Enter your Linktree username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://linktr.ee/",
      allowed_hosts: "linktr.ee,www.linktr.ee",
      path_regex: nil,
      icon_name: "link",
      builtin_icon: "linktree",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Linktree",
      builtin: true,
    },
    {
      key: "pornhub",
      position: "25",
      enabled: true,
      label: "Pornhub",
      user_instructions: "Enter your Pornhub username/handle without @, or paste a full HTTPS URL for this platform.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.pornhub.com/users/",
      allowed_hosts: "pornhub.com,.pornhub.com",
      path_regex: nil,
      icon_name: "globe",
      builtin_icon: "pornhub",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Pornhub",
      builtin: true,
    },
    {
      key: "amazon_wishlist",
      position: "26",
      enabled: true,
      label: "Amazon Wishlist",
      user_instructions: "Enter the full HTTPS URL to your Amazon Wishlist profile or page.",
      placeholder: "https://...",
      input_type: "url_any_https",
      base_url: nil,
      allowed_hosts: "amzn.to,.amazon.com,.amazon.co.uk,.amazon.de,.amazon.nl,.amazon.fr,.amazon.it,.amazon.es,.amazon.ca,.amazon.com.au",
      path_regex: nil,
      icon_name: "fab-amazon",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: "Amazon Wishlist",
      builtin: true,
    },

    {
      key: "reddit",
      position: "27",
      enabled: true,
      label: "Reddit",
      user_instructions: "Enter your Reddit username without u/, or paste your full Reddit profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.reddit.com/user/",
      allowed_hosts: "reddit.com,www.reddit.com,old.reddit.com",
      path_regex: "^/(?:user|u)/[^/?#]+/?$",
      icon_name: "fab-reddit-alien",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "snapchat",
      position: "28",
      enabled: true,
      label: "Snapchat",
      user_instructions: "Enter your Snapchat username without @, or paste your full public profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.snapchat.com/add/",
      allowed_hosts: "snapchat.com,www.snapchat.com",
      path_regex: "^/add/[^/?#]+/?$",
      icon_name: "fab-snapchat",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "pinterest",
      position: "29",
      enabled: true,
      label: "Pinterest",
      user_instructions: "Enter your Pinterest username without @, or paste your full profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.pinterest.com/",
      allowed_hosts: "pinterest.com,www.pinterest.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "fab-pinterest-p",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "kick",
      position: "30",
      enabled: true,
      label: "Kick",
      user_instructions: "Enter your Kick username without @, or paste your full channel URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://kick.com/",
      allowed_hosts: "kick.com,www.kick.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "kick",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "patreon",
      position: "31",
      enabled: true,
      label: "Patreon",
      user_instructions: "Enter your Patreon creator page name, or paste your full creator page URL.",
      placeholder: "creator name or https://...",
      input_type: "handle",
      base_url: "https://www.patreon.com/",
      allowed_hosts: "patreon.com,www.patreon.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "fab-patreon",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "kofi",
      position: "32",
      enabled: true,
      label: "Ko-fi",
      user_instructions: "Enter your Ko-fi username, or paste your full Ko-fi page URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://ko-fi.com/",
      allowed_hosts: "ko-fi.com,www.ko-fi.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "kofi",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "buymeacoffee",
      position: "33",
      enabled: true,
      label: "Buy Me a Coffee",
      user_instructions: "Enter your Buy Me a Coffee username, or paste your full page URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://buymeacoffee.com/",
      allowed_hosts: "buymeacoffee.com,www.buymeacoffee.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "buymeacoffee",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "beacons",
      position: "34",
      enabled: true,
      label: "Beacons",
      user_instructions: "Enter your Beacons username, or paste your full Beacons page URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://beacons.ai/",
      allowed_hosts: "beacons.ai,www.beacons.ai",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "beacons",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "medium",
      position: "35",
      enabled: true,
      label: "Medium",
      user_instructions: "Enter your Medium username without @, or paste a Medium profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://medium.com/@",
      allowed_hosts: ".medium.com",
      path_regex: nil,
      icon_name: "fab-medium",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "deviantart",
      position: "36",
      enabled: true,
      label: "DeviantArt",
      user_instructions: "Enter your DeviantArt username without @, or paste your full profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.deviantart.com/",
      allowed_hosts: "deviantart.com,www.deviantart.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "fab-deviantart",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "vimeo",
      position: "37",
      enabled: true,
      label: "Vimeo",
      user_instructions: "Enter your Vimeo profile slug or user ID slug, or paste your full Vimeo profile URL.",
      placeholder: "profile name or https://...",
      input_type: "handle",
      base_url: "https://vimeo.com/",
      allowed_hosts: "vimeo.com,www.vimeo.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "fab-vimeo-v",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "flickr",
      position: "38",
      enabled: true,
      label: "Flickr",
      user_instructions: "Enter your Flickr profile alias or NSID, or paste your full Flickr profile URL.",
      placeholder: "alias, NSID or https://...",
      input_type: "handle",
      base_url: "https://www.flickr.com/people/",
      allowed_hosts: "flickr.com,www.flickr.com",
      path_regex: "^/people/[^/?#]+/?$",
      icon_name: "fab-flickr",
      builtin_icon: nil,
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "chaturbate",
      position: "39",
      enabled: true,
      label: "Chaturbate",
      user_instructions: "Enter your Chaturbate username, or paste your full profile or room URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://chaturbate.com/p/",
      allowed_hosts: "chaturbate.com,www.chaturbate.com",
      path_regex: "^/(?:p/)?[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "chaturbate",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "manyvids",
      position: "40",
      enabled: true,
      label: "ManyVids",
      user_instructions: "Paste the full HTTPS URL to your ManyVids profile.",
      placeholder: "https://www.manyvids.com/Profile/...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "manyvids.com,www.manyvids.com",
      path_regex: "^/Profile/\\d+/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "manyvids",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "loyalfans",
      position: "41",
      enabled: true,
      label: "LoyalFans",
      user_instructions: "Enter your LoyalFans creator URL name without @, or paste your full creator profile URL.",
      placeholder: "creator name or https://...",
      input_type: "handle",
      base_url: "https://www.loyalfans.com/",
      allowed_hosts: "loyalfans.com,www.loyalfans.com",
      path_regex: "^/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "loyalfans",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "clips4sale",
      position: "42",
      enabled: true,
      label: "Clips4Sale",
      user_instructions: "Enter your numeric Clips4Sale studio ID, or paste your full studio URL.",
      placeholder: "studio ID or https://...",
      input_type: "numeric_id",
      base_url: "https://www.clips4sale.com/studio/",
      allowed_hosts: "clips4sale.com,www.clips4sale.com",
      path_regex: "^/studio/\\d+(?:/[^/?#]+)?/?$",
      icon_name: "globe",
      builtin_icon: "clips4sale",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "iwantclips",
      position: "43",
      enabled: true,
      label: "iWantClips",
      user_instructions: "Paste the full HTTPS URL to your iWantClips store.",
      placeholder: "https://iwantclips.com/store/...",
      input_type: "url_locked",
      base_url: nil,
      allowed_hosts: "iwantclips.com,www.iwantclips.com",
      path_regex: "^/store/\\d+/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "iwantclips",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "redgifs",
      position: "44",
      enabled: true,
      label: "RedGIFs",
      user_instructions: "Enter your RedGIFs username without @, or paste your full user profile URL.",
      placeholder: "username or https://...",
      input_type: "handle",
      base_url: "https://www.redgifs.com/users/",
      allowed_hosts: "redgifs.com,www.redgifs.com",
      path_regex: "^/users/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "redgifs",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    {
      key: "xvideos",
      position: "45",
      enabled: true,
      label: "XVideos",
      user_instructions: "Enter your XVideos profile name, or paste your full profile URL.",
      placeholder: "profile name or https://...",
      input_type: "handle",
      base_url: "https://www.xvideos.com/profiles/",
      allowed_hosts: "xvideos.com,www.xvideos.com",
      path_regex: "^/profiles/[^/?#]+/?$",
      icon_name: "globe",
      builtin_icon: "xvideos",
      badge_background: nil,
      badge_background_dark: nil,
      badge_radius: nil,
      color: nil,
      color_dark: nil,
      legacy_user_field_name: nil,
      builtin: true,
    },
    ].freeze
  end
end
